seeds: 0
train: 1
name: MonoPix_CatDog_Default
model: cycleCtrl
dataset_mode: unaligned
which_model_netG: sid_unet_resize_ctrl
which_model_netD: basic
Gnorm: Identity
Dnorm: instance
n_layers_D: 3
fineSize: 256
patchSize: 32
skip: 1
batchSize: 4
gpu_ids:
    - 0
IsRelativeCtrl: 1
margin: 0.5
beta1: 0.5
display_freq: 400
print_freq: 100
niter: 100
save_epoch_freq: 5
niter_decay: 100
no_flip: 0
pseudo_best_enlvl: 1
source_dataset: ACat
target_dataset: BDog
saveD: 0
dataroot: ""
cal_D_Df: 1
cal_G_Df: 1
lambda_df: 0.5


