seeds: 0
train: 1
name: MonoPix_SummerWinter_Default
model: cycleCtrl
dataset_mode: unaligned
which_model_netG: sid_unet_resize_ctrl
which_model_netD: basic
Gnorm: Identity
Dnorm: Identity
n_layers_D: 3
fineSize: 256
patchSize: 32
skip: 1
batchSize: 4
gpu_ids:
    - 0
IsRelativeCtrl: 1
margin: 0.5
grad_clip: 20
beta1: 0.5
display_freq: 80
print_freq: 40
save_epoch_freq: 10
no_flip: 0
pseudo_best_enlvl: 1
source_dataset: A_Winter
target_dataset: B_Summer
saveD: 0
niter: 200
niter_decay: 100
dataroot: ""
cal_D_Df: 1
cal_G_Df: 1
lambda_df: 0.25